### ISSUE TITLE
Norme di progetto - processi di supporto

### ISSUE THREAD

**Issue by EliaBergamin** [6BitBusters/6BitBusters.github.io#73]
### Oggetto di discussione

VI_2024-12-05

### Codice Verbale

VI 8.2, VI 8.6

### Link Verbale

https://6bitbusters.github.io/VI_2024-12-05.pdf

### Indica il ruolo

Amministratore

### Informazioni minime da implementare

- [x] Norme e convenzioni documenti 
- [x] Nome dei requisiti
- [x] Accertamento della qualità
- [x] Verifica
- [x] Validazione

**Comment by emmazgabg7980** [comment]
Norme e convenzioni documenti
 Nome dei requisiti
 Accertamento della qualità
 Verifica
 Validazione
